import type { NextPage } from 'next';

import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-2 container mx-auto bg-white min-h-screen flex items-center justify-center   prose lg:prose-xl flex-col ">
        <h1>Tailwind Starter</h1>
        <p className="text-center">Lorem ipsum dolor sit amet.</p>
      </main>
      <footer></footer>
    </div>
  );
};

export default Home;
